### ISSUE TITLE
amazonaws

### ISSUE THREAD

**Issue by Troglobitten** [UncleRoger33/adobe-blocklist#3]
I found this blocklist but had issues with certain webpages not loading correctly. Turns out it's because this blocklist blocks s3.amazonaws.com which is amazin cloud storage. Might want to remove this
I don't know what exactly adobe would host on there that they couldnt host on their own domains

**Comment by UncleRoger33** [comment]
I've disabled the other **s3*.amazonaws.com** too. It occurs that there were two of them and i disabled only one.

Thanks for the heads up.
